export const offices = [
    { id: 1, name: "Abakaliki" },
    { id: 2, name: "Abeokuta" },
    { id: 3, name: "ABUJA, HQ" },
    { id: 4, name: "Ado Ekiti" },
    { id: 5, name: "Akure" },
    { id: 6, name: "Asaba" },
    { id: 7, name: "Awka" },
    { id: 8, name: "Bauchi" },
    { id: 9, name: "Benin City" },
    { id: 10, name: "Birnin Kebbi" },
    { id: 11, name: "Calabar" },
    { id: 12, name: "Damaturu" },
    { id: 13, name: "Dutse" },
    { id: 14, name: "Enugu" },
    { id: 15, name: "FCT" },
    { id: 16, name: "Gombe" },
    { id: 17, name: "Gusau" },
    { id: 18, name: "Ibadan" },
    { id: 19, name: "Ikeja" },
    { id: 20, name: "Ilorin" },
    { id: 21, name: "Jalingo" },
    { id: 22, name: "Jos" },
    { id: 23, name: "Kaduna" },
    { id: 24, name: "KANO I (MAIN)" },
    { id: 25, name: "KANO II" },
    { id: 26, name: "Katsina" },
    { id: 27, name: "Lafia" },
    { id: 28, name: "Lokoja" },
    { id: 29, name: "Maiduguri" },
    { id: 30, name: "Makurdi" },
    { id: 31, name: "Minna" },
    { id: 32, name: "Oshogbo" },
    { id: 33, name: "Owerri" },
    { id: 34, name: "Port Harcourt" },
    { id: 35, name: "Sokoto" },
    { id: 36, name: "Umuahia" },
    { id: 37, name: "Uyo" },
    { id: 38, name: "Yenagoa" },
    { id: 39, name: "Yola" }
]